# Generated by Django 4.1.5 on 2024-02-13 19:31

import administracion.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('NUMERO_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_Y_APELLIDO', models.CharField(max_length=120)),
                ('DIRECCION', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(blank=True, max_length=120, null=True)),
                ('TELEFONO', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateTimeField(auto_now_add=True, null=True)),
                ('ESTADO', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('redes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes sociales')),
                ('cuit', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), administracion.models.validate_image_size])),
                ('precios_automaticos', models.BooleanField(default=True)),
                ('mostrar_foto', models.BooleanField(default=False)),
                ('moneda', models.CharField(default='$', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField(blank=True, null=True)),
                ('DETALLE', models.CharField(max_length=255)),
                ('TOTAL', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'Gastos fijos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO', models.CharField(max_length=120, unique=True)),
                ('IMAGEN', models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), administracion.models.validate_image_size])),
                ('CANTIDAD', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('UNIDAD_MEDIDA', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('PRECIO_COMPRA', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('RENTABILIDAD', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('PRECIO_VENTA', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('HABILITAR_VENTA', models.BooleanField(default=False)),
                ('CATEGORIA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='InsumoCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(max_length=255)),
                ('RENTABILIDAD', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('UNIDADES_RESULTANTES', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'Productos Compuestos',
            },
        ),
        migrations.CreateModel(
            name='medioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'medio de pago',
                'verbose_name_plural': 'Medios de pago',
            },
        ),
        migrations.CreateModel(
            name='MiTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPRESA', models.CharField(max_length=120)),
                ('NOMBRE', models.CharField(max_length=120)),
                ('DIRECCION', models.CharField(blank=True, max_length=120, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('TELEFONO', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='productocompuestoreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porciones', models.IntegerField(default=1)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.insumocompuesto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto Compuesto',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateTimeField(blank=True, null=True)),
                ('ESTADO', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('FECHA_ENTREGA', models.DateField(null=True)),
                ('VALIDO_HASTA', models.DateField(blank=True, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateTimeField(auto_now=True, null=True)),
                ('CLIENTE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PagosPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOTAL', models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=25)),
                ('CLIENTE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
                ('MEDIO_DE_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.mediodepago')),
                ('PEDIDO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'seccion de pagos',
            },
        ),
        migrations.CreateModel(
            name='PagosCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOTAL', models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=25, null=True)),
                ('COMPRA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.compras')),
                ('MEDIO_DE_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.mediodepago')),
                ('PROVEEDOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'seccion de pagos',
            },
        ),
        migrations.CreateModel(
            name='InsumoInsumoCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('medida_uso', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.insumo')),
                ('insumo_compuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.insumocompuesto')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Carga de Insumos',
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='PROVEEDOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor'),
        ),
        migrations.CreateModel(
            name='ingredientereceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('medida_uso', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos incluidos en presupuesto',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField(auto_now_add=True)),
                ('CANTIDAD', models.DecimalField(decimal_places=2, default=1, max_digits=25)),
                ('PRECIO', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Precio unitario')),
                ('DESCUENTO', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desc (%)')),
                ('ActualizarCosto', models.BooleanField(default=True)),
                ('COMPRA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.compras')),
                ('PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.insumo')),
            ],
            options={
                'verbose_name': 'detalle de compra',
                'verbose_name_plural': 'Detalles de compras',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='PROVEEDOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='ComentarioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateTimeField(auto_now_add=True)),
                ('COMENTARIO', models.CharField(max_length=255, verbose_name='Comentarios')),
                ('VENTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
            ],
            options={
                'verbose_name': 'comentarios',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
