# Generated by Django 4.1.5 on 2024-02-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumocompuesto',
            name='RENTABILIDAD',
        ),
    ]
