# Generated by Django 4.1.5 on 2024-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_remove_insumocompuesto_rentabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuesto',
            name='RENTABILIDAD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
