# Generated by Django 4.1.5 on 2024-02-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_insumocompuesto_rentabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuesto',
            name='HABILITAR_VENTA',
            field=models.BooleanField(default=False),
        ),
    ]
