# Generated by Django 4.1.5 on 2024-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_insumocompuesto_habilitar_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='CODIGO',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='productocompuestoreceta',
        ),
    ]
