# Generated by Django 4.1.5 on 2024-02-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_insumo_codigo_delete_productocompuestoreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='UNIDAD_MEDIDA',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras'), ('Cm3', 'Cm3')], default='Unidades', max_length=10),
        ),
        migrations.AlterField(
            model_name='insumoinsumocompuesto',
            name='medida_uso',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras'), ('Cm3', 'Cm3')], default='Unidades', max_length=10),
        ),
        migrations.CreateModel(
            name='insumoCompuestoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('insumoCompuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.insumocompuesto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
            ],
            options={
                'verbose_name': 'Producto compuesto',
                'verbose_name_plural': 'Productos Compuesto incluidos',
            },
        ),
    ]
