# Generated by Django 4.1.5 on 2024-02-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_insumo_unidad_medida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumocompuestoreceta',
            old_name='insumoCompuesto',
            new_name='insumo_Compuesto',
        ),
        migrations.RemoveField(
            model_name='insumocompuestoreceta',
            name='precio_unitario',
        ),
    ]
