# Generated by Django 4.1.5 on 2024-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_rename_insumocompuesto_insumocompuestoreceta_insumo_compuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuestoreceta',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
