# Generated by Django 4.1.5 on 2024-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_insumocompuestoreceta_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumocompuestoreceta',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
