# Generated by Django 4.1.5 on 2024-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_insumocompuestoreceta_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumocompuestoreceta',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='insumocompuestoreceta',
            name='precio_unitario_back',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
