# Generated by Django 4.1.5 on 2024-02-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_configuracion_mostrar_stock_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuesto',
            name='CATEGORIA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria'),
        ),
    ]
