# Generated by Django 4.1.5 on 2024-02-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_insumocompuesto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoinsumocompuesto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
        ),
    ]
