# Generated by Django 4.1.5 on 2024-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_insumoinsumocompuesto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='UNIDAD_MEDIDA',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras'), ('Mts', 'Mts')], default='Unidades', max_length=10),
        ),
        migrations.AlterField(
            model_name='insumoinsumocompuesto',
            name='medida_uso',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras'), ('Mts', 'Mts')], default='Unidades', max_length=10),
        ),
    ]
