# Generated by Django 4.1.5 on 2024-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_insumoinsumocompuesto_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='HABILITAR_CC',
            field=models.BooleanField(default=False),
        ),
    ]
