# Generated by Django 4.1.5 on 2024-02-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_cliente_habilitar_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagospedidos',
            name='MEDIO_DE_PAGO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.mediodepago'),
        ),
    ]
