# Generated by Django 4.1.5 on 2024-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_alter_ingredientereceta_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='DESCUENTO',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compras',
            name='ESTADO',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='cuit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='ingredientereceta',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='insumocompuestoreceta',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
