# Generated by Django 4.1.5 on 2024-04-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_pedido_descuento_alter_compras_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='DESCUENTO',
            field=models.FloatField(default=0),
        ),
    ]
