# Generated by Django 4.1.5 on 2024-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_alter_pedido_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientereceta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
