# Generated by Django 5.0.6 on 2024-06-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_alter_insumocompuesto_unidades_resultantes_fabrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='ESTADO',
            field=models.BooleanField(default=False),
        ),
    ]
