# Generated by Django 5.0.6 on 2024-06-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_alter_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoinsumocompuesto',
            name='insumo_compuesto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_referencia', to='administracion.insumocompuesto'),
        ),
        migrations.AlterField(
            model_name='insumoinsumocompuesto',
            name='insumo_compuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_principal', to='administracion.insumocompuesto'),
        ),
    ]
