# Generated by Django 5.0.6 on 2024-06-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_insumoinsumocompuesto_insumo_compuesto_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoinsumocompuesto',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo_insumo', to='administracion.insumo'),
        ),
    ]
