# Generated by Django 5.0.6 on 2024-06-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_alter_insumoinsumocompuesto_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoCompuestoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=20)),
                ('insumo_compuesto_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_principal', to='administracion.insumocompuesto')),
                ('insumo_compuesto_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_referencia', to='administracion.insumocompuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Insumo Compuesto',
                'verbose_name_plural': 'Detalles de Insumos Compuestos',
            },
        ),
    ]
