# Generated by Django 5.0.6 on 2024-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_insumocompuestodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='moneda_secundaria',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
