# Generated by Django 4.1.5 on 2024-08-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_configuracion_moneda_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='fabricar_negativo',
            field=models.BooleanField(default=True),
        ),
    ]
