# Generated by Django 4.1.5 on 2024-08-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_configuracion_fabricar_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='pisar_costo_inferior',
            field=models.BooleanField(default=False),
        ),
    ]
