# Generated by Django 5.0.7 on 2024-09-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0031_configuracion_pisar_costo_inferior'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuesto',
            name='PRECIO_VENTA_UNITARIO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
