# Generated by Django 5.0.7 on 2024-09-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_alter_insumocompuesto_precio_venta_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='FECHA',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
