# Generated by Django 5.0.7 on 2024-09-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0035_pedido_costos_totales_pedido_ingresos_totales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='COSTOS_TOTALES',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='INGRESOS_TOTALES',
        ),
    ]
